[personal]
name = "Advik"
summary = "Polyglot Programmer"
phone = "+91 701 736 4209"
email = "adviksingh6632@gmail.com"
github = "github.com/adv1k"
linkedin = "linkedin.com/in/advik-singh"
twitter = "twitter.com/ThisIsAdvik"
portfolio = "advik.one"

[[education]]
name = "Amity University Noida"
degree = "Bachelor of Technology in Computer Science"
location = "Noida, India"
date = "Aug 2021 - May 2025"

# EXPERIENCE

[[experience]]
role = "Backend Intern"
name = "Aftershoot AI"
location = "Delhi, India"
date = "Feb 2024 - June 2024"
points = [
    "Optimized Python-based photo editing app serving 25,000+ professional photographers, implementing performance improvements that reduced processing times by 40% across key editing workflows.",
    "Developed comprehensive unit and integration tests for Golang microservices using TestContainers, adding 85% test coverage and reducing production incidents by half.",
]

[[experience]]
role = "Backend Intern"
name = "Credible Informatics"
location = "Delhi, India"
date = "May 2023 - Jan 2024"
points = [
    "Built Portfolio Pal from conceptual design to production-ready API serving 3,500+ active users, transforming abstract requirements into a financial data platform processing 50,000+ daily requests with 99.5% uptime.",
    "Developed AI analytics dashboard enabling real-time financial insights, processing 15,000+ daily AI queries with custom prompt engineering to deliver contextual market analysis.",
    "Deployed scalable containerized infrastructure on Fly.io using Docker with Redis caching, implementing monitoring with Sentry to achieve sub-200ms API response times and comprehensive error tracking.",
]

[[experience]]
role = "Backend Intern"
name = "The One World"
location = "Delhi, India"
date = "Apr 2022 - Oct 2022"
points = [
    "Migrated AWS Amplify app to FastAPI serving 8,000+ users, reducing infra costs by 35% and improving API response times by 60% using optimized database queries and redis caching.",
    "Implemented JWT authentication and Google OAuth supporting 12,000+ registered users, with session management, rate limiting, and comprehensive audit logging for enhanced security.",
    "Built geospatial PostgreSQL function using Haversine Formula to enable proximity-based shop discovery, processing 5,000+ daily location queries within 100km radius with sub-500ms response times.",
]

# PROJECTS

[[projects]]
name = "Linux Playground"
skills = "Go, Firecracker, WebSocket, gRPC"
url = "github.com/adv1k/linux-playground"
date = ""
points = [
    "Built a web app to run lightweight Linux VMs with terminal access using Firecracker microVM and xterm.js",
    "Wrote a custom Go init system for the microVM that handles gRPC commands over vsock",
    "Wrote another Go service to manage VM lifecycle and proxy commands over WebSocket",
    "Built the frontend UI using Templ, Tailwind, and HTMX",
]


[[projects]]
name = "Protohacks"
skills = "Go, Python, Sockets, TCP, UDP"
url = "github.com/adv1k/protohacks"
date = ""
points = [
    "Built custom TCP and UDP servers, to solve solve network programming challenges from protohackers.com",
    "Wrote a minimal framework for writing async TCP/UDP servers with route handling, and multiple dispatch",
    "Wrote a binary serialization library for defining binary message layouts with python type hints",
]


[[projects]]
name = "Expensify"
skills = "Typescript, Next.js, Drizzle ORM, Tailwind"
url = "expensify.advik.one"
date = ""
points = [
    "Built full-stack expense tracking application with modern React architecture, featuring responsive design
optimized for mobile usage",
    "Designed intuitive user interface with Tailwind CSS and DaisyUI component",
    "Implemented type-safe database operations using Drizzle ORM with PostgreSQL"
]

# SKILLS

[[skills]]
category = "Languages"
skills = "Python, Go, Typescript, Javascript"

[[skills]]
category = "Frameworks"
skills = "Next.js, Django, FastAPI, Scrapy"

[[skills]]
category = "Databases"
skills = "PostgreSQL, MongoDB, SQLite"

[[skills]]
category = "Developer Tools"
skills = "Docker, Kubernetes, ArgoCD, Prometheus, Grafana, Envoy"
