[personal]
name = "Advik"
summary = "Polyglot Programmer"
phone = "+91 701 736 4209"
email = "adviksingh6632@gmail.com"
github = "github.com/adv1k"
linkedin = "linkedin.com/in/advik-singh"
twitter = "twitter.com/ThisIsAdvik"
portfolio = "advik.one"

[[education]]
name = "Amity University Noida"
degree = "Bachelor of Technology in Computer Science"
location = "Noida, India"
date = "Aug 2021 - May 2025"

# EXPERIENCE

[[experience]]
role = "Backend Developer"
name = "Aftershoot AI"
location = "Delhi, India"
date = "Feb 2024 - June 2024"
points = [
    "Maintained and optimized Python-based photo editing application serving 25,000+ professional photographers, implementing critical bug fixes and performance improvements that reduced processing times by 40% across key editing workflows.",
    "Contributed to Python to Rust migration project by refactoring 8+ core image processing modules, helping achieve 3x performance gains while ensuring API compatibility with existing client integrations and maintaining zero downtime during transitions.",
    "Developed comprehensive unit and integration tests for Golang microservices using TestContainers, improving test coverage from 45% to 85% and reducing production incidents by 50% through robust testing infrastructure.",
]

[[experience]]
role = "Backend Developer"
name = "Credible Informatics"
location = "Delhi, India"
date = "May 2023 - Jan 2024"
points = [
    "Built Portfolio Pal from conceptual design to production-ready API serving 3,500+ active users, transforming abstract requirements into a robust financial data platform processing 50,000+ daily requests with 99.5% uptime.",
    "Deployed scalable containerized infrastructure on Fly.io using Docker with Redis caching, implementing monitoring with Sentry to achieve sub-200ms API response times and comprehensive error tracking across 10+ microservices.",
    "Developed intelligent AI-powered analytics dashboard enabling real-time financial insights, processing 15,000+ daily AI queries with custom prompt engineering to deliver contextual market analysis and automated portfolio recommendations.",
]

[[experience]]
role = "Backend Developer"
name = "The One World"
location = "Delhi, India"
date = "Apr 2022 - Oct 2022"
points = [
    "Contributed to backend migration from AWS Amplify to FastAPI serving 8,000+ users, helping reduce infrastructure costs by 35% and improve API response times by 60% through implementing optimized database queries, connection pooling, and caching strategies.",
    "Implemented JWT authentication and Google OAuth integration features supporting 12,000+ registered users, enabling secure user login functionality with session management, rate limiting, and comprehensive audit logging for enhanced security.",
    "Developed PostgreSQL function using Haversine Formula for geospatial shop discovery, enabling location-based search functionality within 100km radius serving 5,000+ daily location queries with sub-500ms response times for improved user experience.",
]

# PROJECTS

[[projects]]
name = "PortfolioPal"
skills = "Python, FastAPI, Scrapy, Docker, PostgreSQL"
url = ""
date = ""
points = [
    "Engineered comprehensive stock market analytics platform aggregating real-time financial data from 15+ sources including MoneyControl, Yahoo Finance, and YouTube, processing 100,000+ data points daily.",
    "Built sophisticated data pipeline using Scrapy with custom middleware, implementing deduplication algorithms, sentiment analysis, and automated anomaly detection before PostgreSQL storage via optimized batch operations.",
    "Deployed production-grade FastAPI application with Redis caching layer, achieving 150ms average response times and serving personalized financial insights to 1,500+ active traders through RESTful endpoints.",
]

[[projects]]
name = "Expensify"
skills = "Next.js, Drizzle ORM, Tailwind CSS, TypeScript"
url = "expensify.advik.one"
date = ""
points = [
    "Built full-stack expense tracking application with modern React architecture, featuring responsive design optimized for mobile and desktop usage.",
    "Implemented type-safe database operations using Drizzle ORM with PostgreSQL, enabling real-time expense categorization, budget tracking, and financial analytics with sub-100ms query performance.",
    "Designed intuitive user interface with Tailwind CSS and DaisyUI components, incorporating data visualization charts, expense trends analysis, and automated spending insights to improve user financial awareness.",
]

[[projects]]
name = "Resume Automation"
skills = "Python, Typst, GitHub Actions"
url = "resume.advik.one"
date = ""
points = [
    "Developed automated resume generation system transforming structured YAML data into professional PDFs",
    "Published Python package (pip install advik), featuring rich terminal-based resume display with interactive navigation and color-coded sections for enhanced readability.",
    "Architected CI/CD pipeline using GitHub Actions for automated building and publishing (resume.advik.one)",
]

# SKILLS

[[skills]]
category = "Languages"
skills = "Python, Go, Typescript, Javascript"

[[skills]]
category = "Frameworks"
skills = "Next.js, Django, FastAPI, Scrapy"

[[skills]]
category = "Databases"
skills = "PostgreSQL, MongoDB, SQLite"

[[skills]]
category = "Developer Tools"
skills = "Docker, Kubernetes, ArgoCD, Prometheus, Grafana, Envoy"
