[personal]
name = "Advik"
summary = "Polyglot Programmer"
phone = "+91 701 736 4209"
email = "adviksingh6632@gmail.com"
github = "github.com/adv1k"
linkedin = "linkedin.com/in/advik-singh"
twitter = "twitter.com/ThisIsAdvik"
portfolio = "advik.one"

[[education]]
name = "Amity University Noida"
degree = "Bachelor of Technology in Computer Science"
location = "Noida, India"
date = "Aug 2021 - May 2025"

# EXPERIENCE

[[experience]]
role = "Backend Intern"
name = "Aftershoot AI"
location = "Delhi, India"
date = "Feb 2024 - June 2024"
points = [
    "Profiled and optimized a Python photo editing app using flamegraphs and performance tools, reducing workflow times by 20%",
    "Increased reliability of Golang microservices by adding 85% test coverage with TestContainers, cutting production incidents by 50%",
]

[[experience]]
role = "Backend Intern"
name = "Credible Informatics"
location = "Delhi, India"
date = "May 2023 - Jan 2024"
points = [
    "Built AI dashboard for a financial analytics platform to analyze quarterly earnings calls and stock news with sub-200ms APIs",
    "Set up automated CI/CD pipelines for fast deployments, integrated Redis caching and Sentry for reliable error tracking"
]

[[experience]]
role = "Backend Intern"
name = "The One World"
location = "Delhi, India"
date = "Apr 2022 - Oct 2022"
points = [
    "Contributed to migrating AWS Amplify app to FastAPI, reducing infra costs by 35% and improving API latency by 60%",
    "Implemented JWT and Google OAuth for 10,000+ users with rate limiting and audit logging",
    "Built a geospatial PostgreSQL function for proximity-based shop discovery with sub-500ms responses",
]

# PROJECTS

[[projects]]
name = "Linux Playground"
skills = "Go, Firecracker, WebSocket, gRPC"
url = "github.com/adv1k/linux-playground"
date = ""
points = [
    "Built a web app to run lightweight Linux VMs with terminal access using Firecracker microVM and xterm.js",
    "Wrote a custom Go init system for the microVM that handles gRPC commands over vsock",
    "Wrote another Go service to manage VM lifecycle and proxy commands over WebSocket",
]


[[projects]]
name = "Protohacks"
skills = "Go, Python, Sockets, TCP, UDP"
url = "github.com/adv1k/protohacks"
date = ""
points = [
    "Built custom TCP and UDP servers, to solve solve network programming challenges from protohackers.com",
    "Wrote a minimal framework for writing async TCP/UDP servers with route handling, and multiple dispatch",
    "Wrote a binary serialization library for defining binary message layouts with python type hints",
]


[[projects]]
name = "Expensify"
skills = "Typescript, Next.js, Drizzle ORM, Tailwind"
url = "expensify.advik.one"
date = ""
points = [
    "Built full-stack expense tracking application with modern React architecture, featuring responsive design optimized for mobile usage",
    "Designed intuitive user interface with Tailwind CSS and DaisyUI component",
]

# SKILLS

[[skills]]
category = "Languages"
skills = "Python, Go, Typescript, Javascript"

[[skills]]
category = "Frameworks"
skills = "Next.js, Django, FastAPI, Scrapy"

[[skills]]
category = "Databases"
skills = "PostgreSQL, MongoDB, SQLite"

[[skills]]
category = "Developer Tools"
skills = "Docker, Kubernetes, ArgoCD, Prometheus, Grafana, Envoy"
